// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMessage() {
  return window['go']['main']['App']['GetMessage']();
}

export function GetNames() {
  return window['go']['main']['App']['GetNames']();
}
